name: Android CI

on:
  push:
    paths-ignore:
      - .gitignore

jobs:
  buildApkFile:
    name: Build Debug APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          
      - name: Allow gradlew permission
        run: chmod +x ./gradlew
        
      - name: Set up firebase
        shell: bash 
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_ANALYTICS }}
        if: ${{ env.GOOGLE_SERVICES_JSON != '' }}
        run: |
          printf 'GOOGLE_ANALYTICS<<EOF\n%s\nEOF\n' "$GOOGLE_SERVICES_JSON" >> $GITHUB_ENV

      - name: Build debug APK
        run: ./gradlew assembleDebug
          
      - name: Upload debug APK
        uses: actions/upload-artifact@v3
        with:
          name: DrangonIDE Apk
          path: app/build/outputs/apk/debug
